// Package session holds the per-RSP-session state Aether's SM-DP+
// maintains between the four ES9+ messages of a single profile
// download (SGP.22 §3.1, Annex A).
//
// State machine (simplified):
//
//	Initiated → Authenticated → Bound → Notified → Closed
//
// Storage is pluggable via the Store interface. The default
// implementation is in-memory; the Redis-backed store lands in a
// follow-up alongside the rest of the production-ready persistence
// work.
package session

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"sync"
	"time"
)

// State names a point in the session lifecycle.
type State string

const (
	StateInitiated     State = "initiated"
	StateAuthenticated State = "authenticated"
	StateBound         State = "bound"
	StateNotified      State = "notified"
	StateClosed        State = "closed"
)

// Session captures everything an SM-DP+ remembers about an in-flight
// profile download.
type Session struct {
	TransactionID string
	State         State
	CreatedAt     time.Time
	UpdatedAt     time.Time

	// EUICCChallenge from initiateAuthentication. Echoed in the
	// signed serverSigned1 to bind subsequent messages to this session.
	EUICCChallenge []byte

	// ServerChallenge generated by us, also part of serverSigned1.
	ServerChallenge []byte

	// MatchingID assigned by the BSS via ES2+ DownloadOrder; passed in
	// when the session was provisioned by the gateway.
	MatchingID string

	// ICCID of the profile bound to this session.
	ICCID string

	// EUICCCertDER is the eUICC's leaf certificate, captured at
	// authenticateClient time when verification succeeded. Used at
	// getBoundProfilePackage time to verify the signed
	// PrepareDownloadResponse the LPA forwards (§5.7.7).
	EUICCCertDER []byte
}

// Store is the contract for session persistence. Implementations must
// be safe for concurrent use.
type Store interface {
	Create(s *Session) error
	Get(transactionID string) (*Session, error)
	Update(s *Session) error
	Delete(transactionID string) error
}

// ErrNotFound is returned when a transactionID has no session.
var ErrNotFound = errors.New("session: not found")

// MemoryStore is the default in-memory store. Sessions evict on a
// configurable TTL (default 10 minutes per SGP.22 §A.1 implementation
// guidance).
type MemoryStore struct {
	mu  sync.Mutex
	bag map[string]*Session
	ttl time.Duration
}

// NewMemoryStore returns a fresh MemoryStore with the given TTL.
// Zero TTL means sessions live until explicitly deleted.
func NewMemoryStore(ttl time.Duration) *MemoryStore {
	return &MemoryStore{bag: make(map[string]*Session), ttl: ttl}
}

func (s *MemoryStore) Create(sess *Session) error {
	if sess.TransactionID == "" {
		return errors.New("session: empty transactionID")
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.bag[sess.TransactionID] = sess
	return nil
}

func (s *MemoryStore) Get(tid string) (*Session, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	sess, ok := s.bag[tid]
	if !ok {
		return nil, ErrNotFound
	}
	if s.ttl > 0 && time.Since(sess.UpdatedAt) > s.ttl {
		delete(s.bag, tid)
		return nil, ErrNotFound
	}
	return sess, nil
}

func (s *MemoryStore) Update(sess *Session) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, ok := s.bag[sess.TransactionID]; !ok {
		return ErrNotFound
	}
	sess.UpdatedAt = time.Now()
	s.bag[sess.TransactionID] = sess
	return nil
}

func (s *MemoryStore) Delete(tid string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.bag, tid)
	return nil
}

// NewTransactionID returns a 128-bit hex transaction id.
func NewTransactionID() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err)
	}
	return hex.EncodeToString(b[:])
}
