// Package sgp22 contains ASN.1 type definitions and codecs for the
// GSMA SGP.22 Consumer RSP Technical Specification.
//
// Two codec paths are supported:
//
//  1. Pure Go via encoding/asn1, used for types that fit cleanly in
//     Go's ASN.1 model. These types live in this package directly.
//  2. C generated by asn1c, called via cgo, for types where Go's
//     encoding/asn1 cannot represent the schema fully. Generated
//     bindings land under a sub-package once a type requires that
//     path.
//
// Every exported type carries a doc comment naming the SGP.22 section
// it implements. This is deliberate: the codebase reads as a free
// reference for the spec.
package sgp22
